# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 273a0c5b5de261d42d830d5055b096a71d3b6cb8cb6138122da8ff8dce218915547be655d24890d7bcc56e548b01f69c7f3663e6c7679eb9cb3aa25291a36343

test:
  secret_key_base: 1ec59ffa53edc9edb20c7ddcd70f4dbdbcbd6bb6736437e120fd2a53e38ba96164ff4d36bcdbf7e64fdbc1f8691597fa6b8b5d0dcb2e5022a9061021d9a3b0fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
